# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad84dbe0441efa6f730aa4bf48eef9bf9d3912ad9fea195f42201217913aebeb2ebcdc92633039e0b62321e235c924457635357a341c246fd207e391d1ae954

test:
  secret_key_base: 5155bf10432d699116c5936e0b893a8af24da754719e7b8b93a9d30e683017540b4c9feaad3251607167ea7b877cd733d40740a6da4303399aeffa4daaf21072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
